#!/usr/bin/env bash
set -e -x

rm -rf ./webapp/dist

git worktree add -f webapp/dist master

time npm run build --prefix ./webapp

cd ./webapp/dist

git add --all
git commit -a -m "dist"
git push origin master
